import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-payroll-tax-notice-suta-rate-audit",
  "engine": "recovery",
  "title": "Payroll Tax Notice & SUTA Rate Audit",
  "shortTitle": "Payroll Tax Recovery",
  "tagline": "Resolve tax notices, correct unemployment rates, and recover payroll-tax overpayments",
  "industry": "Payroll Tax Compliance & Recovery",
  "uiPort": 4566,
  "apiPort": 5566,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Payroll-tax assessments and rate errors resolved with agency-ready evidence",
  "valueNarrative": "Connect legal entities, jurisdictions, payroll registers, filings, deposits, notices, SUTA rate notices, benefit charges, and agency accounts.",
  "calculation": {
    "actualKey": "assessedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Assessed or paid amount",
    "expectedLabel": "Supported tax liability",
    "varianceLabel": "Potential tax recovery",
    "direction": "actual-minus-expected",
    "finding": "Payroll, filing, deposit, notice, and unemployment-rate evidence indicate an unsupported tax assessment or overpayment.",
    "actions": [
      "Reconcile payroll, filing, deposit, and agency account data",
      "Validate SUTA rate components and benefit charges",
      "Prepare notice response, amendment, or refund claim",
      "Track agency resolution and reconcile account credit"
    ]
  }
},[
feature("entity-and-jurisdiction-registry","PTR01","Entity and jurisdiction registry","Reconcile entity and jurisdiction registry using entity registrations, payroll registers, tax filings, deposits, agency notices, SUTA rates, wage bases, benefit charges, and account transcripts.","Produce a governed entity and jurisdiction registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Tax Agency / State","text","State Workforce Agency"],["noticeAccount","Notice / Account","text","NTC-88412 / UI-1948"],["assessedAmount","Assessed / Paid Amount","currency",318000],["supportedAmount","Supported Liability","currency",226500]],{amountField:"assessedAmount",subjects:["Federal payroll tax notice","State withholding notice","SUTA rate notice","Benefit charge statement","Local payroll tax assessment"]}),
feature("payroll-register-ingestion","PTR02","Payroll register ingestion","Reconcile payroll register ingestion using entity registrations, payroll registers, tax filings, deposits, agency notices, SUTA rates, wage bases, benefit charges, and account transcripts.","Produce a governed payroll register ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Tax Agency / State","text","State Workforce Agency"],["noticeAccount","Notice / Account","text","NTC-88412 / UI-1948"],["assessedAmount","Assessed / Paid Amount","currency",318000],["supportedAmount","Supported Liability","currency",226500]],{amountField:"assessedAmount",subjects:["Federal payroll tax notice","State withholding notice","SUTA rate notice","Benefit charge statement","Local payroll tax assessment"]}),
feature("return-and-deposit-reconciliation","PTR03","Return and deposit reconciliation","Reconcile return and deposit reconciliation using entity registrations, payroll registers, tax filings, deposits, agency notices, SUTA rates, wage bases, benefit charges, and account transcripts.","Produce a governed return and deposit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Tax Agency / State","text","State Workforce Agency"],["noticeAccount","Notice / Account","text","NTC-88412 / UI-1948"],["assessedAmount","Assessed / Paid Amount","currency",318000],["supportedAmount","Supported Liability","currency",226500]],{amountField:"assessedAmount",subjects:["Federal payroll tax notice","State withholding notice","SUTA rate notice","Benefit charge statement","Local payroll tax assessment"]}),
feature("agency-notice-intake","PTR04","Agency notice intake","Reconcile agency notice intake using entity registrations, payroll registers, tax filings, deposits, agency notices, SUTA rates, wage bases, benefit charges, and account transcripts.","Produce a governed agency notice intake decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Tax Agency / State","text","State Workforce Agency"],["noticeAccount","Notice / Account","text","NTC-88412 / UI-1948"],["assessedAmount","Assessed / Paid Amount","currency",318000],["supportedAmount","Supported Liability","currency",226500]],{amountField:"assessedAmount",subjects:["Federal payroll tax notice","State withholding notice","SUTA rate notice","Benefit charge statement","Local payroll tax assessment"]}),
feature("notice-deadline-control","PTR05","Notice deadline control","Reconcile notice deadline control using entity registrations, payroll registers, tax filings, deposits, agency notices, SUTA rates, wage bases, benefit charges, and account transcripts.","Produce a governed notice deadline control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Tax Agency / State","text","State Workforce Agency"],["noticeAccount","Notice / Account","text","NTC-88412 / UI-1948"],["assessedAmount","Assessed / Paid Amount","currency",318000],["supportedAmount","Supported Liability","currency",226500]],{amountField:"assessedAmount",subjects:["Federal payroll tax notice","State withholding notice","SUTA rate notice","Benefit charge statement","Local payroll tax assessment"]}),
feature("suta-rate-validation","PTR06","SUTA rate validation","Reconcile suta rate validation using entity registrations, payroll registers, tax filings, deposits, agency notices, SUTA rates, wage bases, benefit charges, and account transcripts.","Produce a governed suta rate validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Tax Agency / State","text","State Workforce Agency"],["noticeAccount","Notice / Account","text","NTC-88412 / UI-1948"],["assessedAmount","Assessed / Paid Amount","currency",318000],["supportedAmount","Supported Liability","currency",226500]],{amountField:"assessedAmount",subjects:["Federal payroll tax notice","State withholding notice","SUTA rate notice","Benefit charge statement","Local payroll tax assessment"]}),
feature("experience-rating-calculation","PTR07","Experience-rating calculation","Reconcile experience-rating calculation using entity registrations, payroll registers, tax filings, deposits, agency notices, SUTA rates, wage bases, benefit charges, and account transcripts.","Produce a governed experience-rating calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Tax Agency / State","text","State Workforce Agency"],["noticeAccount","Notice / Account","text","NTC-88412 / UI-1948"],["assessedAmount","Assessed / Paid Amount","currency",318000],["supportedAmount","Supported Liability","currency",226500]],{amountField:"assessedAmount",subjects:["Federal payroll tax notice","State withholding notice","SUTA rate notice","Benefit charge statement","Local payroll tax assessment"]}),
feature("benefit-charge-audit","PTR08","Benefit charge audit","Reconcile benefit charge audit using entity registrations, payroll registers, tax filings, deposits, agency notices, SUTA rates, wage bases, benefit charges, and account transcripts.","Produce a governed benefit charge audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Tax Agency / State","text","State Workforce Agency"],["noticeAccount","Notice / Account","text","NTC-88412 / UI-1948"],["assessedAmount","Assessed / Paid Amount","currency",318000],["supportedAmount","Supported Liability","currency",226500]],{amountField:"assessedAmount",subjects:["Federal payroll tax notice","State withholding notice","SUTA rate notice","Benefit charge statement","Local payroll tax assessment"]}),
feature("wage-base-and-rate-validation","PTR09","Wage-base and rate validation","Reconcile wage-base and rate validation using entity registrations, payroll registers, tax filings, deposits, agency notices, SUTA rates, wage bases, benefit charges, and account transcripts.","Produce a governed wage-base and rate validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Tax Agency / State","text","State Workforce Agency"],["noticeAccount","Notice / Account","text","NTC-88412 / UI-1948"],["assessedAmount","Assessed / Paid Amount","currency",318000],["supportedAmount","Supported Liability","currency",226500]],{amountField:"assessedAmount",subjects:["Federal payroll tax notice","State withholding notice","SUTA rate notice","Benefit charge statement","Local payroll tax assessment"]}),
feature("multi-state-allocation-review","PTR10","Multi-state allocation review","Reconcile multi-state allocation review using entity registrations, payroll registers, tax filings, deposits, agency notices, SUTA rates, wage bases, benefit charges, and account transcripts.","Produce a governed multi-state allocation review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Tax Agency / State","text","State Workforce Agency"],["noticeAccount","Notice / Account","text","NTC-88412 / UI-1948"],["assessedAmount","Assessed / Paid Amount","currency",318000],["supportedAmount","Supported Liability","currency",226500]],{amountField:"assessedAmount",subjects:["Federal payroll tax notice","State withholding notice","SUTA rate notice","Benefit charge statement","Local payroll tax assessment"]}),
feature("penalty-and-interest-recalculation","PTR11","Penalty and interest recalculation","Reconcile penalty and interest recalculation using entity registrations, payroll registers, tax filings, deposits, agency notices, SUTA rates, wage bases, benefit charges, and account transcripts.","Produce a governed penalty and interest recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Tax Agency / State","text","State Workforce Agency"],["noticeAccount","Notice / Account","text","NTC-88412 / UI-1948"],["assessedAmount","Assessed / Paid Amount","currency",318000],["supportedAmount","Supported Liability","currency",226500]],{amountField:"assessedAmount",subjects:["Federal payroll tax notice","State withholding notice","SUTA rate notice","Benefit charge statement","Local payroll tax assessment"]}),
feature("agency-response-package","PTR12","Agency response package","Reconcile agency response package using entity registrations, payroll registers, tax filings, deposits, agency notices, SUTA rates, wage bases, benefit charges, and account transcripts.","Produce a governed agency response package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Tax Agency / State","text","State Workforce Agency"],["noticeAccount","Notice / Account","text","NTC-88412 / UI-1948"],["assessedAmount","Assessed / Paid Amount","currency",318000],["supportedAmount","Supported Liability","currency",226500]],{amountField:"assessedAmount",subjects:["Federal payroll tax notice","State withholding notice","SUTA rate notice","Benefit charge statement","Local payroll tax assessment"]}),
feature("amended-return-and-refund-claim","PTR13","Amended return and refund claim","Reconcile amended return and refund claim using entity registrations, payroll registers, tax filings, deposits, agency notices, SUTA rates, wage bases, benefit charges, and account transcripts.","Produce a governed amended return and refund claim decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Tax Agency / State","text","State Workforce Agency"],["noticeAccount","Notice / Account","text","NTC-88412 / UI-1948"],["assessedAmount","Assessed / Paid Amount","currency",318000],["supportedAmount","Supported Liability","currency",226500]],{amountField:"assessedAmount",subjects:["Federal payroll tax notice","State withholding notice","SUTA rate notice","Benefit charge statement","Local payroll tax assessment"]}),
feature("agency-case-and-credit-tracking","PTR14","Agency case and credit tracking","Reconcile agency case and credit tracking using entity registrations, payroll registers, tax filings, deposits, agency notices, SUTA rates, wage bases, benefit charges, and account transcripts.","Produce a governed agency case and credit tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Tax Agency / State","text","State Workforce Agency"],["noticeAccount","Notice / Account","text","NTC-88412 / UI-1948"],["assessedAmount","Assessed / Paid Amount","currency",318000],["supportedAmount","Supported Liability","currency",226500]],{amountField:"assessedAmount",subjects:["Federal payroll tax notice","State withholding notice","SUTA rate notice","Benefit charge statement","Local payroll tax assessment"]}),
feature("tax-exposure-and-outcome-analytics","PTR15","Tax exposure and outcome analytics","Reconcile tax exposure and outcome analytics using entity registrations, payroll registers, tax filings, deposits, agency notices, SUTA rates, wage bases, benefit charges, and account transcripts.","Produce a governed tax exposure and outcome analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Tax Agency / State","text","State Workforce Agency"],["noticeAccount","Notice / Account","text","NTC-88412 / UI-1948"],["assessedAmount","Assessed / Paid Amount","currency",318000],["supportedAmount","Supported Liability","currency",226500]],{amountField:"assessedAmount",subjects:["Federal payroll tax notice","State withholding notice","SUTA rate notice","Benefit charge statement","Local payroll tax assessment"]})
]);
